// <auto-generated />
using System;
using Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final.Data.Migrations.Shop
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final.Entity.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseTopic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            Name = "Ciceklisogukhavadeposu"
                        });
                });

            modelBuilder.Entity("Final.Entity.CompanyRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleId = "role-ciceklisogukhavadeposu"
                        });
                });

            modelBuilder.Entity("Final.Entity.MqttTool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ToolBaseTopic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("MqttTools", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Main control room for the company",
                            Name = "Control Room"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Compressor tool",
                            Name = "Compressor"
                        });
                });

            modelBuilder.Entity("Final.Entity.MqttTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseTopic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Data64")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<int>("HowMany")
                        .HasColumnType("int");

                    b.Property<Guid?>("MqttToolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TopicPurpose")
                        .HasColumnType("int");

                    b.Property<string>("TopicTemplate")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("MqttToolId");

                    b.ToTable("MqttTopics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 3,
                            HowMany = 1,
                            MqttToolId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/compressor/status"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa0-aaaa-aaaa-aaaa-000000000001"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 3,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "pwr_rqst/room1/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa0-aaaa-aaaa-aaaa-000000000002"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 3,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "pwr_rqst/room2/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa0-aaaa-aaaa-aaaa-000000000003"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 3,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "pwr_rqst/room3/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa0-aaaa-aaaa-aaaa-000000000004"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 3,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "pwr_rqst/room4/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa0-aaaa-aaaa-aaaa-000000000005"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 3,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "pwr_rqst/room5/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa0-aaaa-aaaa-aaaa-000000000006"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 3,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "pwr_rqst/room6/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa0-aaaa-aaaa-aaaa-000000000007"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 3,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "pwr_rqst/room7/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa0-aaaa-aaaa-aaaa-000000000008"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 3,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "pwr_rqst/room8/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa0-aaaa-aaaa-aaaa-000000000009"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 3,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "pwr_rqst/room9/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa0-aaaa-aaaa-aaaa-00000000000a"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 3,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "pwr_rqst/room10/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa0-aaaa-aaaa-aaaa-00000000000b"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 3,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "pwr_rqst/room11/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa0-aaaa-aaaa-aaaa-00000000000c"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 3,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "pwr_rqst/room12/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000001"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "set_temp/room1/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000002"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "set_temp/room2/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000003"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "set_temp/room3/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000004"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "set_temp/room4/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000005"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "set_temp/room5/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000006"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "set_temp/room6/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000007"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "set_temp/room7/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000008"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "set_temp/room8/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000009"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "set_temp/room9/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-00000000000a"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "set_temp/room10/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-00000000000b"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "set_temp/room11/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-00000000000c"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 1,
                            TopicTemplate = "set_temp/room12/control_room/ciceklisogukhavadeposu"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000001"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room1/status"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000002"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room2/status"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000003"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room3/status"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000004"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room4/status"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000005"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room5/status"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000006"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room6/status"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000007"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room7/status"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000008"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room8/status"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000009"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room9/status"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-00000000000a"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room10/status"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-00000000000b"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room11/status"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-00000000000c"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 12,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room12/status"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 1,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room1/temp"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 1,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room2/temp"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 1,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room3/temp"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 1,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room4/temp"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 1,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room5/temp"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 1,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room6/temp"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 1,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room7/temp"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 1,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room8/temp"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 1,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room9/temp"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000a"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 1,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room10/temp"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000b"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 1,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room11/temp"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000c"),
                            BaseTopic = "ciceklisogukhavadeposu",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Data64 = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            DataType = 8,
                            HowMany = 1,
                            MqttToolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TopicPurpose = 0,
                            TopicTemplate = "ciceklisogukhavadeposu/control_room/room12/temp"
                        });
                });

            modelBuilder.Entity("Final.Entity.CompanyRole", b =>
                {
                    b.HasOne("Final.Entity.Company", "Company")
                        .WithMany("CompanyRoles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Final.Entity.MqttTool", b =>
                {
                    b.HasOne("Final.Entity.Company", "Company")
                        .WithMany("Tools")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Final.Entity.MqttTopic", b =>
                {
                    b.HasOne("Final.Entity.Company", "Company")
                        .WithMany("Topics")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Final.Entity.MqttTool", "MqttTool")
                        .WithMany("Topics")
                        .HasForeignKey("MqttToolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("MqttTool");
                });

            modelBuilder.Entity("Final.Entity.Company", b =>
                {
                    b.Navigation("CompanyRoles");

                    b.Navigation("Tools");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Final.Entity.MqttTool", b =>
                {
                    b.Navigation("Topics");
                });
#pragma warning restore 612, 618
        }
    }
}
